[package]
name = "wasm-tests"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = false
repository = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ['cdylib']

[dev-dependencies]
# `fuels` intentionally not specified through `workspace=true`. In
# the workspace cargo.toml `fuels` has default features enabled (so
# that our examples don't inherit `fuels` with disabled features).
# Cargo wouldn't respect any attempts here to disable them again.
fuels = { path = "../fuels", default-features = false }
fuels-core = { path = "../fuels-core", default-features = false }
getrandom = { version = "0.2.11", features = ["js"] }
wasm-bindgen-test = "0.3.39"
