[workspace]
members = [
  'sway/bindings/sharing_types/contract_a',
  'sway/bindings/sharing_types/contract_b',
  'sway/bindings/sharing_types/shared_lib',
  'sway/bindings/simple_contract',
  'sway/bindings/type_paths',
  'sway/contracts/asserts',
  'sway/contracts/auth_testing_abi',
  'sway/contracts/auth_testing_contract',
  'sway/contracts/block_timestamp',
  'sway/contracts/configurables',
  'sway/contracts/contract_test',
  'sway/contracts/huge_contract',
  'sway/contracts/large_return_data',
  'sway/contracts/lib_contract',
  'sway/contracts/lib_contract_abi',
  'sway/contracts/lib_contract_caller',
  'sway/contracts/library_test',
  'sway/contracts/liquidity_pool',
  'sway/contracts/low_level_caller',
  'sway/contracts/msg_methods',
  'sway/contracts/multiple_read_calls',
  'sway/contracts/needs_custom_decoder',
  'sway/contracts/payable_annotation',
  'sway/contracts/proxy',
  'sway/contracts/revert_transaction_error',
  'sway/contracts/storage',
  'sway/contracts/token_ops',
  'sway/contracts/transaction_block_height',
  'sway/contracts/tx_input_output',
  'sway/contracts/var_outputs',
  'sway/logs/contract_logs',
  'sway/logs/contract_logs_abi',
  'sway/logs/contract_revert_logs',
  'sway/logs/contract_with_contract_logs',
  'sway/logs/script_heap_logs',
  'sway/logs/script_logs',
  'sway/logs/script_revert_logs',
  'sway/logs/script_with_contract_logs',
  'sway/predicates/basic_predicate',
  'sway/predicates/predicate_blobs',
  'sway/predicates/predicate_configurables',
  'sway/predicates/predicate_witnesses',
  'sway/predicates/signatures',
  'sway/predicates/swap',
  'sway/predicates/predicate_tx_input_output',
  'sway/scripts/arguments',
  'sway/scripts/basic_script',
  'sway/scripts/empty',
  'sway/scripts/require_from_contract',
  'sway/scripts/reverting',
  'sway/scripts/script_array',
  'sway/scripts/script_asserts',
  'sway/scripts/script_blobs',
  'sway/scripts/script_configurables',
  'sway/scripts/script_enum',
  'sway/scripts/script_needs_custom_decoder',
  'sway/scripts/script_proxy',
  'sway/scripts/script_struct',
  'sway/scripts/script_tx_input_output',
  'sway/scripts/transfer_script',
  'sway/types/contracts/b256',
  'sway/types/contracts/b512',
  'sway/types/contracts/bytes',
  'sway/types/contracts/call_empty_return',
  'sway/types/contracts/complex_types_contract',
  'sway/types/contracts/empty_arguments',
  'sway/types/contracts/enum_as_input',
  'sway/types/contracts/enum_encoding',
  'sway/types/contracts/enum_inside_struct',
  'sway/types/contracts/evm_address',
  'sway/types/contracts/generics',
  'sway/types/contracts/heap_type_in_enums',
  'sway/types/contracts/heap_types',
  'sway/types/contracts/identity',
  'sway/types/contracts/native_types',
  'sway/types/contracts/nested_structs',
  'sway/types/contracts/options',
  'sway/types/contracts/raw_slice',
  'sway/types/contracts/results',
  'sway/types/contracts/std_lib_string',
  'sway/types/contracts/str_in_array',
  'sway/types/contracts/string_slice',
  'sway/types/contracts/tuples',
  'sway/types/contracts/two_structs',
  'sway/types/contracts/type_inside_enum',
  'sway/types/contracts/u128',
  'sway/types/contracts/u256',
  'sway/types/contracts/vector_output',
  'sway/types/contracts/vectors',
  'sway/types/predicates/address',
  'sway/types/predicates/enums',
  'sway/types/predicates/predicate_b256',
  'sway/types/predicates/predicate_bytes',
  'sway/types/predicates/predicate_bytes_hash',
  'sway/types/predicates/predicate_generics',
  'sway/types/predicates/predicate_raw_slice',
  'sway/types/predicates/predicate_std_lib_string',
  'sway/types/predicates/predicate_string_slice',
  'sway/types/predicates/predicate_tuples',
  'sway/types/predicates/predicate_u128',
  'sway/types/predicates/predicate_u256',
  'sway/types/predicates/predicate_vector',
  'sway/types/predicates/predicate_vectors',
  'sway/types/predicates/structs',
  'sway/types/predicates/u64',
  'sway/types/scripts/options_results',
  'sway/types/scripts/script_b256',
  'sway/types/scripts/script_bytes',
  'sway/types/scripts/script_generics',
  'sway/types/scripts/script_heap_types',
  'sway/types/scripts/script_raw_slice',
  'sway/types/scripts/script_std_lib_string',
  'sway/types/scripts/script_string_slice',
  'sway/types/scripts/script_tuples',
  'sway/types/scripts/script_u128',
  'sway/types/scripts/script_u256',
  'sway/types/scripts/script_vectors',
]

[patch.'https://github.com/fuellabs/sway']
std = { git = "https://github.com/fuellabs/sway", branch = "ironcev/error-codes-in-abi-json" }
