[workspace]
members = [
  'tests/bindings/sharing_types/contract_a',
  'tests/bindings/sharing_types/contract_b',
  'tests/bindings/sharing_types/shared_lib',
  'tests/bindings/simple_contract',
  'tests/bindings/type_paths',
  'tests/contracts/asserts',
  'tests/contracts/auth_testing_abi',
  'tests/contracts/auth_testing_contract',
  'tests/contracts/block_timestamp',
  'tests/contracts/configurables',
  'tests/contracts/contract_test',
  'tests/contracts/large_return_data',
  'tests/contracts/lib_contract',
  'tests/contracts/lib_contract_abi',
  'tests/contracts/lib_contract_caller',
  'tests/contracts/library_test',
  'tests/contracts/liquidity_pool',
  'tests/contracts/low_level_caller',
  'tests/contracts/msg_amount',
  'tests/contracts/multiple_read_calls',
  'tests/contracts/needs_custom_decoder',
  'tests/contracts/payable_annotation',
  'tests/contracts/require',
  'tests/contracts/revert_transaction_error',
  'tests/contracts/storage',
  'tests/contracts/token_ops',
  'tests/contracts/transaction_block_height',
  'tests/logs/contract_logs',
  'tests/logs/contract_logs_abi',
  'tests/logs/contract_with_contract_logs',
  'tests/logs/script_experimental_logs',
  'tests/logs/script_logs',
  'tests/logs/script_needs_custom_decoder_logging',
  'tests/logs/script_with_contract_logs',
  'tests/predicates/basic_predicate',
  'tests/predicates/predicate_configurables',
  'tests/predicates/predicate_witnesses',
  'tests/predicates/signatures',
  'tests/predicates/swap',
  'tests/scripts/arguments',
  'tests/scripts/basic_script',
  'tests/scripts/require_from_contract',
  'tests/scripts/script_array',
  'tests/scripts/script_asserts',
  'tests/scripts/script_configurables',
  'tests/scripts/script_enum',
  'tests/scripts/script_needs_custom_decoder',
  'tests/scripts/script_require',
  'tests/scripts/script_struct',
  'tests/scripts/transfer_script',
  'tests/types/contracts/b256',
  'tests/types/contracts/b512',
  'tests/types/contracts/bytes',
  'tests/types/contracts/call_empty_return',
  'tests/types/contracts/complex_types_contract',
  'tests/types/contracts/empty_arguments',
  'tests/types/contracts/enum_as_input',
  'tests/types/contracts/enum_encoding',
  'tests/types/contracts/enum_inside_struct',
  'tests/types/contracts/evm_address',
  'tests/types/contracts/generics',
  'tests/types/contracts/heap_type_in_enums',
  'tests/types/contracts/heap_types',
  'tests/types/contracts/identity',
  'tests/types/contracts/native_types',
  'tests/types/contracts/nested_structs',
  'tests/types/contracts/options',
  'tests/types/contracts/raw_slice',
  'tests/types/contracts/results',
  'tests/types/contracts/std_lib_string',
  'tests/types/contracts/str_in_array',
  'tests/types/contracts/string_slice',
  'tests/types/contracts/tuples',
  'tests/types/contracts/two_structs',
  'tests/types/contracts/type_inside_enum',
  'tests/types/contracts/u128',
  'tests/types/contracts/u256',
  'tests/types/contracts/vector_output',
  'tests/types/contracts/vectors',
  'tests/types/predicates/address',
  'tests/types/predicates/enums',
  'tests/types/predicates/predicate_b256',
  'tests/types/predicates/predicate_bytes',
  'tests/types/predicates/predicate_bytes_hash',
  'tests/types/predicates/predicate_generics',
  'tests/types/predicates/predicate_raw_slice',
  'tests/types/predicates/predicate_std_lib_string',
  'tests/types/predicates/predicate_tuples',
  'tests/types/predicates/predicate_u128',
  'tests/types/predicates/predicate_u256',
  'tests/types/predicates/predicate_vector',
  'tests/types/predicates/predicate_vectors',
  'tests/types/predicates/structs',
  'tests/types/predicates/u64',
  'tests/types/scripts/options_results',
  'tests/types/scripts/script_b256',
  'tests/types/scripts/script_bytes',
  'tests/types/scripts/script_generics',
  'tests/types/scripts/script_heap_types',
  #TODO: Decide what to do with this test project once
  # https://github.com/FuelLabs/sway/issues/5145 is resolved
  # 'tests/types/scripts/script_raw_slice',
  'tests/types/scripts/script_std_lib_string',
  'tests/types/scripts/script_tuples',
  'tests/types/scripts/script_u128',
  'tests/types/scripts/script_u256',
  'tests/types/scripts/script_vectors',
]

[patch.'https://github.com/fuellabs/sway']
std = { git = "https://github.com/fuellabs/sway", branch = "hal3e/call_with_fn_selector" }
